Web/RecruitMe.Web/Controllers/CandidatesController.cs
namespace RecruitMe.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RecruitMe.Common;
    using RecruitMe.Data.Models;
    using RecruitMe.Services.Data;
    using RecruitMe.Web.Infrastructure.Attributes;
    using RecruitMe.Web.ViewModels.Candidates;
    using RecruitMe.Web.ViewModels.JobOffers;
    using RecruitMe.Web.ViewModels.Shared;

    [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
    public class CandidatesController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICandidatesService candidatesService;
        private readonly IFileExtensionsService fileExtensionsService;
        private readonly ILanguagesService languagesService;
        private readonly ISkillsService skillsService;
        private readonly IJobOffersService jobOffersService;
        private readonly IEmployersService employersService;
        private readonly IEnumerable<string> allowedExtensions;
        private readonly IEnumerable<LanguagesDropDownCheckboxListViewModel> languages;
        private readonly IEnumerable<SkillsDropDownCheckboxListViewModel> skills;

        public CandidatesController(
            UserManager<ApplicationUser> userManager,
            ICandidatesService candidatesService,
            IFileExtensionsService fileExtensionsService,
            ILanguagesService languagesService,
            ISkillsService skillsService,
            IJobOffersService jobOffersService,
            IEmployersService employersService)
        {
            this.userManager = userManager;
            this.candidatesService = candidatesService;
            this.fileExtensionsService = fileExtensionsService;
            this.languagesService = languagesService;
            this.skillsService = skillsService;
            this.jobOffersService = jobOffersService;
            this.employersService = employersService;
            this.allowedExtensions = this.fileExtensionsService.GetImageExtensions();
            this.languages = this.languagesService.GetAll<LanguagesDropDownCheckboxListViewModel>();
            this.skills = this.skillsService.GetAll<SkillsDropDownCheckboxListViewModel>();
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (!this.User.Identity.IsAuthenticated)
            {
                this.HttpContext.Session.SetString("UserRole", GlobalConstants.CandidateRoleName);
            }

            var viewModel = new IndexViewModel();
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId != null)
            {
                viewModel.IsProfileCreated = true;
            }

            var lastTenOffers = this.jobOffersService.GetLastTenOffers<IndexJobOffersModel>();
            var topEmployers = this.employersService.GetTopFiveEmployers<IndexTopEmployersModel>();
            viewModel.LastTenJobOffers = lastTenOffers;
            viewModel.TopEmployers = topEmployers;
            return this.View(viewModel);
        }

        public IActionResult MyProfile()
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction(nameof(this.CreateProfile));
            }

            var viewModel = this.candidatesService.GetProfileDetails<ProfileViewModel>(candidateId);

            return this.View(viewModel);
        }

        public IActionResult CreateProfile()
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId != null)
            {
                return this.RedirectToAction(nameof(this.UpdateProfile));
            }

            var viewModel = new CreateCandidateProfileInputModel
            {
                ImageExtensions = this.allowedExtensions,
                Languages = this.languages,
                Skills = this.skills,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProfile(CreateCandidateProfileInputModel input)
        {
            if (this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name) != null)
            {
                return this.RedirectToAction(nameof(this.UpdateProfile));
            }

            if (!this.ModelState.IsValid)
            {
                input.ImageExtensions = this.allowedExtensions;
                input.Languages = this.languages;
                input.Skills = this.skills;
                return this.View(input);
            }

            if (input.ProfilePicture != null && !this.allowedExtensions.Any(ae => input.ProfilePicture.FileName.EndsWith(ae)))
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.FileExtensionNotSupported);
                input.ImageExtensions = this.allowedExtensions;
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            input.ApplicationUserId = user.Id;

            var candidateId = await this.candidatesService.CreateProfileAsync(input);
            if (candidateId == null)
            {
                return this.RedirectToAction("Error", "Home");
            }

            user.CandidateId = candidateId;
            await this.userManager.UpdateAsync(user);
            this.TempData["Success"] = GlobalConstants.ProfileSuccessfullyCreated;
            return this.RedirectToAction("Upload", "Documents");
        }

        public IActionResult UpdateProfile()
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction(nameof(this.CreateProfile));
            }

            var details = this.candidatesService.GetProfileDetails<UpdateCandidateProfileViewModel>(candidateId);
            if (details == null)
            {
                return this.NotFound();
            }

            details.ImageExtensions = this.allowedExtensions;
            details.LanguagesList = this.languages;
            details.SkillsList = this.skills;
            return this.View(details);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UpdateCandidateProfileViewModel input)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction(nameof(this.CreateProfile));
            }

            if (!this.ModelState.IsValid)
            {
                input.ImageExtensions = this.allowedExtensions;
                input.LanguagesList = this.languages;
                input.SkillsList = this.skills;
                return this.View(input);
            }

            if (input.ProfilePicture != null && !this.allowedExtensions.Any(ae => input.ProfilePicture.FileName.EndsWith(ae)))
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.FileExtensionNotSupported);
                input.ImageExtensions = this.allowedExtensions;
                return this.View(input);
            }

            var updateResult = await this.candidatesService.UpdateProfileAsync(candidateId, input);

            if (updateResult == null)
            {
                return this.RedirectToAction("Error", "Home");
            }

            this.TempData["Success"] = GlobalConstants.ProfileSuccessfullyUpdated;
            return this.RedirectToAction(nameof(this.MyProfile));
        }
    }
}

Web/RecruitMe.Web/Views/Candidates/CreateProfile.cshtml
@model RecruitMe.Web.ViewModels.Candidates.CreateCandidateProfileInputModel
@{
    ViewData["Title"] = "Create Profile";
    var allowedFileExtensions = string.Join(", ", this.Model.ImageExtensions);
    var languages = Model.Languages.Select(l => new SelectListItem(l.Name, l.Id.ToString())).ToList();
    var skills = Model.Skills.Select(s => new SelectListItem(s.Name, s.Id.ToString())).ToList();
}

<h1 style="display:inline-block">@ViewData["Title"]</h1>
<a class="btn btn-primary float-right" style="margin-right:1rem" asp-area="Identity" asp-controller="Account" asp-action="Manage">Manage Account</a>

<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>

<div class="container-fluid">
    <form class="container" asp-controller="Candidates" asp-action="CreateProfile" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="@Model.ProfilePicture"></label> -
                    <label><small><strong>Allowed file extensions:</strong> @allowedFileExtensions; </small></label>
                    <label><small><strong>Max Size allowed:</strong> 10MB</small></label>
                    <input asp-for="@Model.ProfilePicture" class="form-control" />
                    <span asp-validation-for="@Model.ProfilePicture" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.FirstName"></label>
                    <label class="text-danger float-right"><small><strong>Required</strong></small></label>
                    <input asp-for="@Model.FirstName" class="form-control" />
                    <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.LastName"></label>
                    <label class="text-danger float-right"><small><strong>Required</strong></small></label>
                    <input asp-for="@Model.LastName" class="form-control" />
                    <span asp-validation-for="@Model.LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-6">

                <div class="form-group">
                    <label asp-for="@Model.PhoneNumber"></label> (e.g. +3591234567890)
                    <input asp-for="@Model.PhoneNumber" class="form-control" />
                    <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.ContactAddress"></label>
                    <input asp-for="@Model.ContactAddress" class="form-control" />
                    <span asp-validation-for="@Model.ContactAddress" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Education"></label>
                    <input asp-for="@Model.Education" class="form-control" />
                    <span asp-validation-for="@Model.Education" class="text-danger"></span>
                </div>
            </div>
        </div>
            <div class="form-group">
                <label asp-for="AboutMe"></label>
                <textarea asp-for="AboutMe" class="form-control"></textarea>
                <span asp-validation-for="AboutMe" class="text-danger"></span>
            </div>
        <hr />
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="SkillsIds"></label>
                    <label class="text-danger float-right"><small><strong>Please select at least one</strong></small></label>
                    <select multiple size="5" asp-for="SkillsIds" asp-items="skills" class="form-control"></select>
                    <span asp-validation-for="SkillsIds" class="text-danger"></span>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="LanguagesIds"></label>
                    <label class="text-danger float-right"><small><strong>Please select at least one</strong></small></label>
                    <select multiple size="5" asp-for="LanguagesIds" asp-items="languages" class="form-control"></select>
                    <span asp-validation-for="LanguagesIds" class="text-danger"></span>
                </div>
            </div>
            <input style="margin-left: 1.5rem;" type="submit" value="Submit" class="btn btn-primary" />
            <a class="btn btn-danger" style="margin-left:0.5rem" href="javascript:history.go(-1)">Cancel</a>
        </div>
    </form>
</div>

Web/RecruitMe.Web/Views/Candidates/Index.cshtml
@model RecruitMe.Web.ViewModels.Shared.IndexViewModel
@{
    ViewData["Title"] = "Candidates Homepage";
}

<h1>@ViewData["Title"]</h1>

@if (this.TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<div>
    <h3>Welcome!</h3>
</div>
<hr />
@if (!User.Identity.IsAuthenticated)
{
    <p>Our platform provides access to thousands of job offers posted by leading companies and recruitment agencies operating in all kinds of sectors, from healthcare and education to IT, the entertainment industry, science, construction and many more!</p>

    <p>If you are interested in browsing all of the currently opened positions to find your next career, <a style="display:inline" href="/Identity/Account/Register"><strong>please register here.</strong></a></p>
    <p>If you already have an account, <a style="display:inline" href="/Identity/Account/Login"><strong>please sign in.</strong></a></p>

    <div class="row">
        <div class="card text-center">
            <div class="card-body">
                <h4 class="card-title" style="display:inline-block">Success Stories</h4>
                <hr />
                <p class="card-text"><h6>John Smith, Senior .NET Developer</h6></p>
                <p>Working with Recruit.Me has helped me find my current position as a developer in my dream company. The process was easy and effortless and I would recommend the platform to all of my friends and acquaintances.</p>
            </div>
            <div class="card-body">
                <p class="card-text"><h6>ACME Inc.</h6></p>
                <p>The platform has helped our company hire some of our best employees easily and efficiently, which has brought immense value and know-how to our business not only with our clients, but with our partners as well!</p>
            </div>
        </div>
    </div>
}
else
{
    <p>
        <h5>
            Ready to find your new career?
        </h5>
    </p>
    if (!this.Model.IsProfileCreated)
    {
        <p><h5>Let us know more about you by <a style="display:inline" href="/Candidates/CreateProfile"><strong>filling out your profile details.</strong></a></h5></p>
    }
    else
    {
        <p><h5>Have a look at our latest offers or check out the offers of our top employers, or <a style="display:inline" href="/JobOffers/All"><strong>browse all offers.</strong></a></h5></p>
    }
    <br />
    <hr />
    <partial name="_IndexPartial" model="@Model" />
}

Web/RecruitMe.Web/Views/Candidates/MyProfile.cshtml
@model RecruitMe.Web.ViewModels.Candidates.ProfileViewModel
@{
    ViewData["Title"] = "My Profile";
    string candidateName = this.Model.Name != null ? ", " + this.Model.Name : string.Empty;
    string profilePictureUrl = this.Model.ProfilePictureUrl != null ? this.Model.ProfilePictureUrl : "/img/profile-placeholder.png";
}

<h1>@ViewData["Title"]</h1>

@if (this.TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<div>
    <h3>@("Welcome"+candidateName)</h3>
</div>
<hr />
<div class="row">
    <div class="card">
        <img class="card-img-top img-thumbnail" src="@profilePictureUrl" style="width: 300px; height: 300px;">
    </div>
    <div class="card flex-fill">
        <div class="card-body">
            <h5 class="card-title" style="display:inline-block"><strong>Profile Details:</strong></h5>
            <a class="float-right btn btn-primary" asp-controller="Candidates" asp-action="UpdateProfile">Update profile details</a>
            <div class="card-text"><strong>Name: </strong>@Model.Name</div>
            <div class="card-text"><strong>Email Address: </strong>@Model.ApplicationUserEmail</div>
            <div class="card-text"><strong>Phone Number: </strong>@(Model.PhoneNumber!=null?Model.PhoneNumber:"  -")</div>
            <br />
            <div class="card-text"><strong>Education: </strong>@Model.Education</div>
            <div class="card-text"><strong>Languages: </strong>@(Model.Languages!=string.Empty?Model.Languages : " -")</div>
            <div class="card-text"><strong>Skills: </strong>@(Model.Skills!=string.Empty?Model.Skills : "  -")</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="card flex-fill">
        <div class="card-body">
            <h5 class="card-title" style="display:inline-block"><strong>About Me:</strong></h5>
            <div class="card-text">@(Model.AboutMe!=null?Model.AboutMe:"Nothing to show here.")</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="card flex-fill">
        <div class="card-body">
            <h5 class="card-title" style="display:inline-block"><strong>My Links:</strong></h5>
            <div class="card-text">
                <strong>My Documents:   </strong>
                View and manage your
                <a style="display:inline" href="/Documents/All">
                    <strong>
                        documents portfolio
                    </strong>
                </a>
            </div>
            <div class="card-text">
                <strong>My Job Applications:   </strong>
                Review the history and details of your
                <a style="display:inline" href="/JobApplications/All">
                    <strong>
                        job applications,
                    </strong>
                </a>
                view and manage their current status
            </div>
            <div class="card-text">
                <strong>Account management:   </strong>
                Manage your Recruit.Me account,
                <a style="display:inline" href="/Identity/Account/Manage/ChangePassword">
                    <strong>
                        reset your password
                    </strong>
                </a>
                or
                <a style="display:inline" href="/Identity/Account/Manage/Email">
                    <strong>
                        update your email address
                    </strong>
                </a>
            </div>
        </div>
    </div>
</div>

Web/RecruitMe.Web/Views/Candidates/UpdateProfile.cshtml
@model RecruitMe.Web.ViewModels.Candidates.UpdateCandidateProfileViewModel
@{
    ViewData["Title"] = "Update Profile";
    var allowedFileExtensions = string.Join(", ", this.Model.ImageExtensions);
    var languages = Model.LanguagesList.Select(l => new SelectListItem(l.Name, l.Id.ToString())).ToList();
    var skills = Model.SkillsList.Select(s => new SelectListItem(s.Name, s.Id.ToString())).ToList();
}

<h1 style="display:inline-block">@ViewData["Title"]</h1>
<a class="btn btn-primary float-right" style="margin-right:1rem" asp-area="Identity" asp-controller="Account" asp-action="Manage">Manage Account</a>

<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>

<div class="container-fluid">
    <form class="container" asp-controller="Candidates" asp-action="UpdateProfile" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="ProfilePicture"></label> -
                    <label><small><strong>Allowed file extensions:</strong> @allowedFileExtensions; </small></label>
                    <label><small><strong>Max Size allowed:</strong> 10MB</small></label>
                    <input value="Upload Picture" asp-for="ProfilePicture" class="form-control" />
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="PhoneNumber"></label> (e.g. +3591234567890)
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ContactAddress"></label>
                    <input asp-for="ContactAddress" class="form-control" />
                    <span asp-validation-for="ContactAddress" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Education"></label>
                    <input asp-for="Education" class="form-control" />
                    <span asp-validation-for="Education" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AboutMe"></label>
            <textarea asp-for="AboutMe" class="form-control"></textarea>
            <span asp-validation-for="AboutMe" class="text-danger"></span>
        </div>
        <hr />
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="SkillsIds"></label>
                    <select multiple size="5" asp-for="SkillsIds" asp-items="skills" class="form-control"></select>
                    <span asp-validation-for="SkillsIds" class="text-danger"></span>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="LanguagesIds"></label>
                    <select multiple size="5" asp-for="LanguagesIds" asp-items="languages" class="form-control"></select>
                    <span asp-validation-for="LanguagesIds" class="text-danger"></span>
                </div>
            </div>
            <input style="margin-left: 1.5rem;" type="submit" value="Submit" class="btn btn-primary" />
            <a id="cancelButton" class="btn btn-danger" style="margin-left:0.5rem">Cancel</a>
        </div>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        $("#cancelButton").attr("href", "http://www.google.com/")

        if (window.opener != null) {
            //PopUp
            $("#cancelButton").attr("href", "javascript:window.open('','_self').close()");
        }
        else {
            $("#cancelButton").attr("href", "javascript:history.go(-1)");
        }
    });
</script>