Web/RecruitMe.Web/Controllers/JobOffersController.cs
namespace RecruitMe.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RecruitMe.Common;
    using RecruitMe.Data.Models;
    using RecruitMe.Services.Data;
    using RecruitMe.Web.Infrastructure.Attributes;
    using RecruitMe.Web.ViewModels.Employers;
    using RecruitMe.Web.ViewModels.JobOffers;

    [Authorize]
    public class JobOffersController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IJobOffersService jobOffersService;
        private readonly IEmployersService employersService;
        private readonly IJobSectorsService jobSectorsService;
        private readonly IJobLevelsService jobLevelsService;
        private readonly IJobTypesService jobTypesService;
        private readonly ILanguagesService languagesService;
        private readonly ISkillsService skillsService;

        private readonly IEnumerable<JobSectorsDropDownViewModel> jobSectors;
        private readonly IEnumerable<JobLevelsDropDownViewModel> jobLevels;
        private readonly List<JobTypesDropDownCheckboxListViewModel> jobTypes;
        private readonly IEnumerable<LanguagesDropDownCheckboxListViewModel> languages;
        private readonly IEnumerable<SkillsDropDownCheckboxListViewModel> skills;

        public JobOffersController(
            UserManager<ApplicationUser> userManager,
            IJobOffersService jobOffersService,
            IEmployersService employersService,
            IJobSectorsService jobSectorsService,
            IJobLevelsService jobLevelsService,
            IJobTypesService jobTypesService,
            ILanguagesService languagesService,
            ISkillsService skillsService)
        {
            this.userManager = userManager;
            this.jobOffersService = jobOffersService;
            this.employersService = employersService;
            this.jobSectorsService = jobSectorsService;
            this.jobLevelsService = jobLevelsService;
            this.jobTypesService = jobTypesService;
            this.languagesService = languagesService;
            this.skillsService = skillsService;

            this.jobSectors = this.jobSectorsService.GetAll<JobSectorsDropDownViewModel>();
            this.jobLevels = this.jobLevelsService.GetAll<JobLevelsDropDownViewModel>();
            this.jobTypes = this.jobTypesService.GetAll<JobTypesDropDownCheckboxListViewModel>().ToList();
            this.languages = this.languagesService.GetAll<LanguagesDropDownCheckboxListViewModel>();
            this.skills = this.skillsService.GetAll<SkillsDropDownCheckboxListViewModel>();
        }

        public async Task<IActionResult> All([FromQuery]FilterModel filters, string sortOrder, int page = 1, int perPage = GlobalConstants.ItemsPerPage)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.Search));
            }

            var totalJobOffersCount = this.jobOffersService.GetCount();
            var filteredJobOffers = await this.jobOffersService.GetAllValidFilteredOffersAsync<JobOffersViewModel>(filters);

            if (filteredJobOffers == null)
            {
                return this.RedirectToAction("Error", "Home");
            }

            if (filteredJobOffers.Count() != totalJobOffersCount)
            {
                this.ViewData["IsFromSearch"] = "Search Results";
            }

            this.ViewData["DateSortParam"] = string.IsNullOrEmpty(sortOrder) ? "date_asc" : string.Empty;
            this.ViewData["LevelSortParam"] = sortOrder == "max_level" ? "min_level" : "max_level";

            filteredJobOffers = sortOrder switch
            {
                "max_level" => filteredJobOffers.OrderByDescending(jo => jo.JobLevelId),
                "min_level" => filteredJobOffers.OrderBy(jo => jo.JobLevelId),
                "date_asc" => filteredJobOffers.OrderBy(jo => jo.CreatedOn),
                _ => filteredJobOffers.OrderByDescending(jo => jo.CreatedOn)
            };

            var pagesCount = (int)Math.Ceiling(filteredJobOffers.Count() / (decimal)perPage);

            var paginatedOffers = filteredJobOffers
             .Skip(perPage * (page - 1))
             .Take(perPage)
             .ToList();

            var viewModel = new AllViewModel
            {
                JobOffers = paginatedOffers,
                CurrentPage = page,
                PagesCount = pagesCount,
            };

            return this.View(viewModel);
        }

        public IActionResult Search()
        {
            var filterModel = new FilterModel
            {
                Levels = this.jobLevels,
                Sectors = this.jobSectors,
                Types = this.jobTypes,
                Skills = this.skills,
                Languages = this.languages,
            };

            return this.View(filterModel);
        }

        public IActionResult Details(string id)
        {
            var jobOfferDetails = this.jobOffersService.GetDetails<JobOfferDetailsViewModel>(id);

            if (jobOfferDetails == null)
            {
                return this.NotFound();
            }

            return this.View(jobOfferDetails);
        }

        [AuthorizeRoles(GlobalConstants.EmployerRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult Post()
        {
            var employerId = this.employersService.GetEmployerIdByUsername(this.User.Identity.Name);
            if (employerId == null)
            {
                return this.RedirectToAction("CreateProfile", "Employers");
            }

            var model = new PostViewModel
            {
                JobSectors = this.jobSectors,
                JobLevels = this.jobLevels,
                JobTypesOptions = this.jobTypes,
                Languages = this.languages,
                Skills = this.skills,
            };
            return this.View(model);
        }

        [HttpPost]
        [AuthorizeRoles(GlobalConstants.EmployerRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Post(PostViewModel input)
        {
            var employerId = this.employersService.GetEmployerIdByUsername(this.User.Identity.Name);
            if (employerId == null)
            {
                return this.RedirectToAction("CreateProfile", "Employers");
            }

            var isOfferPositionDuplicate = this.jobOffersService.IsPositionDuplicate(employerId, input.Position);
            if (isOfferPositionDuplicate)
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.JobOfferWithSameNameAlreadyExists);
            }

            if (!this.ModelState.IsValid)
            {
                input.JobSectors = this.jobSectors;
                input.JobLevels = this.jobLevels;
                input.JobTypesOptions = this.jobTypes;
                input.Languages = this.languages;
                input.Skills = this.skills;

                return this.View(input);
            }

            var jobOfferId = await this.jobOffersService.AddAsync(input, employerId);

            if (jobOfferId == null)
            {
                return this.RedirectToAction("Error", "Home");
            }

            this.TempData["Success"] = GlobalConstants.JobOfferSuccessfullyPosted;
            return this.RedirectToAction(nameof(this.All));
        }

        [AuthorizeRoles(GlobalConstants.EmployerRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(string id)
        {
            var employerId = this.employersService.GetEmployerIdByUsername(this.User.Identity.Name);
            if (employerId == null)
            {
                return this.RedirectToAction("CreateProfile", "Employers");
            }

            var isOfferPostedByEmployer = this.jobOffersService.IsOfferPostedByEmployer(id, employerId);
            if (!isOfferPostedByEmployer)
            {
                return this.Forbid();
            }

            var jobOffer = this.jobOffersService.GetDetails<EditJobOfferDetailsModel>(id);

            if (jobOffer == null)
            {
                return this.NotFound();
            }

            var viewModel = new EditViewModel
            {
                JobOfferDetails = jobOffer,
                JobSectors = this.jobSectors,
                JobLevels = this.jobLevels,
                JobTypesOptions = this.jobTypes,
                Languages = this.languages,
                Skills = this.skills,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [AuthorizeRoles(GlobalConstants.EmployerRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(EditViewModel input)
        {
            var employerId = this.employersService.GetEmployerIdByUsername(this.User.Identity.Name);
            if (employerId == null)
            {
                return this.RedirectToAction("CreateProfile", "Employers");
            }

            var isOfferPostedByEmployer = this.jobOffersService.IsOfferPostedByEmployer(input.JobOfferDetails.Id, employerId);
            if (!isOfferPostedByEmployer)
            {
                return this.Forbid();
            }

            if (!this.ModelState.IsValid)
            {
                input.JobSectors = this.jobSectors;
                input.JobLevels = this.jobLevels;
                input.JobTypesOptions = this.jobTypes;
                input.Languages = this.languages;
                input.Skills = this.skills;
                return this.View(input);
            }

            var jobOfferId = await this.jobOffersService.UpdateAsync(input, employerId);

            if (jobOfferId == null)
            {

Web/RecruitMe.Web/Views/JobOffers/All.cshtml
@model RecruitMe.Web.ViewModels.JobOffers.AllViewModel
@using RecruitMe.Common
@{
    ViewData["Title"] = "Current Job Offers";

    var jobOffers = this.Model.JobOffers.ToList();
}
@if (this.ViewData["IsFromSearch"] != null)
{
    <h1 style="display:inline">@ViewData["IsFromSearch"]</h1>
}
else
{
    <h1 style="display:inline">@ViewData["Title"]</h1>
    <a class="btn btn-primary float-right" style="margin-right:1rem" asp-action="Search" asp-controller="JobOffers">Search Offers</a>
}
@if (this.TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="table-responsive">
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th scope="col">Position</th>
                <th scope="col">Employer</th>
                <th scope="col">Position Level <a style="margin: 5px; display:inline" asp-action="All" asp-controller="JobOffers" asp-route-sortOrder="@ViewData["LevelSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Location</th>
                <th scope="col">Published On <a style="margin: 5px;display:inline" asp-action="All" asp-controller="JobOffers" asp-route-sortOrder="@ViewData["DateSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Sector</th>
                <th scope="col">Position Specifics</th>

                <th style="text-align:center">
                    @if (ViewData["IsFromSearch"] != null)
                    {
                        <a class="btn btn-warning" asp-controller="JobOffers" asp-action="Search">Back to Search</a>
                    }
                    else
                    {
                        @if (this.User.IsInRole(GlobalConstants.EmployerRoleName))
                        {
                            <a class="btn btn-success" asp-controller="JobOffers" asp-action="Post">Post New Job Offer</a>
                        }
                    }
                </th>
            </tr>
        </thead>
        <tbody>
            @if (jobOffers.Count == 0)
            {
                <tr>
                    <td>
                        No job offers to show.
                    </td>
                </tr>
            }
            @foreach (var jobOffer in jobOffers)
            {
                <tr>
                    <td class="text-break">@jobOffer.Position</td>
                    <td>@jobOffer.EmployerName</td>
                    <td>@jobOffer.JobLevelName</td>
                    <td>@jobOffer.City</td>
                    <td>@jobOffer.CreatedOn.Date.ToString("dd-MM-yyyy")</td>
                    <td>@jobOffer.JobSectorName</td>
                    <td>@jobOffer.JobDetails</td>
                    <td>
                        <a class="btn btn-info text-nowrap float-right"target="_blank" asp-controller="JobOffers" asp-action="Details" asp-route-id="@jobOffer.Id">View Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <nav>
        <ul class="pagination">
            @if (this.Model.CurrentPage == 1)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-left"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@Model.PreviousPage"><icon class="fas fa-angle-left"></icon></a></li>
            }

            @for (int i = 1; i <= Model.PagesCount; i++)
            {
                var active = i == this.Model.CurrentPage ? "active" : string.Empty;

                <li class="page-item @active"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@i">@i</a></li>
            }

            @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.PagesCount == 0)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-right"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@Model.NextPage"><icon class="fas fa-angle-right"></icon></a></li>
            }
        </ul>
    </nav>
</div>

Web/RecruitMe.Web/Views/JobOffers/ByEmployer.cshtml
@model RecruitMe.Web.ViewModels.JobOffers.ByEmployerViewModel
@using RecruitMe.Common
@{
    ViewData["Title"] = $"Current Job Offers by {Model.Name}";

    var jobOffers = this.Model.JobOffers.ToList();
}

<h1 style="display:inline">@ViewData["Title"]</h1>
<a class="btn btn-warning float-right" href="javascript:history.go(-1)">Back</a>


<div class="table-responsive">
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th scope="col">Position</th>
                <th scope="col">Employer</th>
                <th scope="col">Position Level </th>
                <th scope="col">Location</th>
                <th scope="col">Published On <a style="margin: 5px;display:inline" asp-action="All" asp-controller="JobOffers" asp-route-sortOrder="@ViewData["DateSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Sector</th>
                <th scope="col">Position Specifics</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (jobOffers.Count == 0)
            {
                <tr>
                    <td>
                        No job offers to show.
                    </td>
                </tr>
            }
            @foreach (var jobOffer in jobOffers)
            {
                <tr>
                    <td class="text-break">@jobOffer.Position</td>
                    <td>@jobOffer.EmployerName</td>
                    <td>@jobOffer.JobLevelName</td>
                    <td>@jobOffer.City</td>
                    <td>@jobOffer.CreatedOn.Date.ToString("dd-MM-yyyy")</td>
                    <td>@jobOffer.JobSectorName</td>
                    <td>@jobOffer.JobDetails</td>
                    <td>
                        <a class="btn btn-info text-nowrap" target="_blank" asp-controller="JobOffers" asp-action="Details" asp-route-id="@jobOffer.Id">View Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <nav>
        <ul class="pagination">
            @if (this.Model.CurrentPage == 1)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-left"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@Model.PreviousPage"><icon class="fas fa-angle-left"></icon></a></li>
            }

            @for (int i = 1; i <= Model.PagesCount; i++)
            {
                var active = i == this.Model.CurrentPage ? "active" : string.Empty;

                <li class="page-item @active"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@i">@i</a></li>
            }

            @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.PagesCount == 0)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-right"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobOffers/All?page=@Model.NextPage"><icon class="fas fa-angle-right"></icon></a></li>
            }
        </ul>
    </nav>
</div>

Web/RecruitMe.Web/Views/JobOffers/Delete.cshtml
@model RecruitMe.Web.ViewModels.JobOffers.DeleteViewModel
@{
    ViewData["Title"] = @$"Delete Job Offer";
}

<h1 style="display:inline">@ViewData["Title"]</h1>
<hr />

<h3>Are you sure you want to delete the following job offer?</h3>
<br />
<div>
    <form method="post">
        <div class="form-group">
            <h5><strong>Position: </strong> @Model.Position</h5>
        </div>
        <br />
        <input type="submit" value="Delete" class="btn btn-danger" asp-controller="JobOffers" asp-action="DeleteConfirmed" asp-route-id="@Model.Id" />
        <a href="javascript:window.open('','_self').close()" class="btn btn-warning">Back</a>
    </form>
</div>

Web/RecruitMe.Web/Views/JobOffers/Details.cshtml
@model RecruitMe.Web.ViewModels.JobOffers.JobOfferDetailsViewModel
@using RecruitMe.Common
@{
    ViewData["Title"] = Model.Position;
    var officeAddress = Model.OfficeAddress != null ? ", " + Model.OfficeAddress : string.Empty;
    var jobTypes = string.Join("; ", Model.JobTypes);
    var languages = string.Join("; ", Model.Languages);
    var skills = string.Join("; ", Model.Skills);
}

<h1>@ViewData["Title"]</h1>

<a style ="display:inline" class="btn btn-warning float-right" href="javascript:window.open('','_self').close()">Close</a>
@if (this.User.Identity.Name == Model.EmployerApplicationUserUserName)
{
    <a style ="display:inline" class="btn btn-info float-right"  asp-controller="JobOffers" asp-action="Edit" asp-route-id="@Model.Id">Edit Details</a>
}
<br />
<hr />
<div class="card">
    <div class="card-body">
        <h5 class="card-title" style="display:inline-block">Position Details:</h5>
        <p class="card-text"><strong>Employer: </strong>@Model.EmployerName</p>
        <p class="card-text"><strong>City: </strong>@Model.City; <strong>Position Level: </strong>@Model.JobLevelName;<strong>Type: </strong>@jobTypes; <strong>Sector: </strong>@Model.JobSectorName</p>
        @if (Model.Salary.HasValue)
        {
            <p class="card-text"><strong>Salary: </strong>@Model.Salary € </p>
        }

        <p class="card-text"><strong>Required Languages: </strong>@languages; <strong>Required Skills: </strong>@skills </p>
    </div>
</div>
<hr />
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Position Description:</h5>
        <p class="card-text">@Html.Raw(Model.Description)</p>
        @if (this.User.IsInRole(GlobalConstants.CandidateRoleName))
        {
            <div class="text-center">
                <a class="btn btn-success align-center" asp-controller="JobApplications" asp-action="Apply" asp-route-jobOfferId="@Model.Id">Apply</a>
            </div>
        }

    </div>
</div>

Web/RecruitMe.Web/Views/JobOffers/Edit.cshtml
@model RecruitMe.Web.ViewModels.JobOffers.EditViewModel
@{
    ViewData["Title"] = @$"Edit Job Offer details for ""{Model.JobOfferDetails.Position}""";

    var jobSectors = Model.JobSectors.Select(js => new SelectListItem(js.Name, js.Id.ToString()));
    var jobLevels = Model.JobLevels.Select(jl => new SelectListItem(jl.Name, jl.Id.ToString()));
    var jobTypes = Model.JobTypesOptions.Select(jt => new SelectListItem(jt.Name, jt.Id.ToString())).ToList();
    var languages = Model.Languages.Select(l => new SelectListItem(l.Name, l.Id.ToString())).ToList();
    var skills = Model.Skills.Select(s => new SelectListItem(s.Name, s.Id.ToString())).ToList();
}

<h1>@ViewData["Title"]</h1>

<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>

<div class="container-fluid">
    <form id="inputForm" class="container" asp-controller="JobOffers" asp-action="Edit" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div>
            <div>
                <div class="form-group">
                    <input hidden asp-for="JobOfferDetails.Id" class="form-control" value="@Model.JobOfferDetails.Id" />
                    <label asp-for="JobOfferDetails.Position"></label>
                    <input asp-for="JobOfferDetails.Position" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.Position" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.Description"></label>
                    <textarea asp-for="JobOfferDetails.Description" class="form-control"></textarea>
                    <span asp-validation-for="JobOfferDetails.Description" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="JobOfferDetails.City"></label>
                    <input asp-for="JobOfferDetails.City" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.OfficeAddress"></label>
                    <input asp-for="JobOfferDetails.OfficeAddress" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.OfficeAddress" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.Salary"></label> (in €)
                    <input asp-for="JobOfferDetails.Salary" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.Salary" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.JobSectorId"></label>
                    <select asp-for="JobOfferDetails.JobSectorId" asp-items="jobSectors" class="form-control"></select>
                    <span asp-validation-for="JobOfferDetails.JobSectorId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.JobLevelId"></label>
                    <select asp-for="JobOfferDetails.JobLevelId" asp-items="jobLevels" class="form-control"></select>
                    <span asp-validation-for="JobOfferDetails.JobLevelId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobOfferDetails.ValidFrom"></label>
                    <input id="ValidFrom" type="date" readonly="@DateTime.UtcNow.Date.ToString("dd-MM-yyyy")" asp-for="JobOfferDetails.ValidFrom" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.ValidFrom" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="JobOfferDetails.ValidUntil"></label>
                    <input id="ValidTo" type="date" readonly="@DateTime.UtcNow.Date.ToString("dd-MM-yyyy")" asp-for="JobOfferDetails.ValidUntil" class="form-control" />
                    <span asp-validation-for="JobOfferDetails.ValidUntil" class="text-danger"></span>
                </div>
                <input type="submit" value="Update Details" class="btn btn-primary" style="margin-left: 1.5rem;" />
                <a class="btn btn-warning" style="margin-left: 0.5rem;" href="javascript:window.open('','_self').close()">Cancel</a>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="JobOfferDetails.SkillsIds"></label>
                    <select multiple size="5" asp-for="JobOfferDetails.SkillsIds" asp-items="skills" class="form-control"></select>
                    <span asp-validation-for="JobOfferDetails.SkillsIds" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobOfferDetails.LanguagesIds"></label>
                    <select multiple size="5" asp-for="JobOfferDetails.LanguagesIds" asp-items="languages" class="form-control"></select>
                    <span asp-validation-for="JobOfferDetails.LanguagesIds" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobOfferDetails.JobTypesIds"></label>
                    <select multiple size="5" asp-for="JobOfferDetails.JobTypesIds" asp-items="jobTypes" class="form-control"></select>
                    <span asp-validation-for="JobOfferDetails.JobTypesIds" class="text-danger"></span>
                </div>
            </div>
        </div>
    </form>
</div>