Web/RecruitMe.Web/Controllers/JobApplicationsController.cs
namespace RecruitMe.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RecruitMe.Common;
    using RecruitMe.Data.Models;
    using RecruitMe.Services.Data;
    using RecruitMe.Web.Infrastructure.Attributes;
    using RecruitMe.Web.ViewModels.JobApplications;

    [Authorize]
    public class JobApplicationsController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IJobApplicationService jobApplicationService;
        private readonly IJobOffersService jobOffersService;
        private readonly ICandidatesService candidatesService;
        private readonly IEmployersService employersService;
        private readonly IDocumentsService documentsService;
        private readonly IJobApplicationStatusesService jobApplicationStatusesService;

        public JobApplicationsController(UserManager<ApplicationUser> userManager, IJobApplicationService jobApplicationService, IJobOffersService jobOffersService, ICandidatesService candidatesService, IEmployersService employersService, IDocumentsService documentsService, IJobApplicationStatusesService jobApplicationStatusesService)
        {
            this.userManager = userManager;
            this.jobApplicationService = jobApplicationService;
            this.jobOffersService = jobOffersService;
            this.candidatesService = candidatesService;
            this.employersService = employersService;
            this.documentsService = documentsService;
            this.jobApplicationStatusesService = jobApplicationStatusesService;
        }

        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult Apply(string jobOfferId)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            var candidateDetails = this.candidatesService.GetProfileDetails<CandidateContactDetailsViewModel>(candidateId);
            var candidateDocumentDetails = this.documentsService.GetAllDocumentsForCandidate<CandidateDocumentsDropDownViewModel>(candidateId);
            var jobOfferDetails = this.jobOffersService.GetDetails<JobApplicationJobOfferDetailsViewModel>(jobOfferId);

            if (candidateDetails == null || candidateDocumentDetails == null || jobOfferDetails == null)
            {
                return this.NotFound();
            }

            var viewModel = new ApplyViewModel
            {
                CandidateDetails = candidateDetails,
                Documents = candidateDocumentDetails,
                JobOfferDetails = jobOfferDetails,
                JobOfferId = jobOfferId,
                CandidateId = candidateId,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Apply(ApplyViewModel input)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            if (!this.ModelState.IsValid)
            {
                var candidateDetails = this.candidatesService.GetProfileDetails<CandidateContactDetailsViewModel>(input.CandidateId);
                var candidateDocumentDetails = this.documentsService.GetAllDocumentsForCandidate<CandidateDocumentsDropDownViewModel>(input.CandidateId);
                var jobOfferDetails = this.jobOffersService.GetDetails<JobApplicationJobOfferDetailsViewModel>(input.JobOfferId);

                input.CandidateDetails = candidateDetails;
                input.Documents = candidateDocumentDetails;
                input.JobOfferDetails = jobOfferDetails;
                return this.View(input);
            }

            if (this.jobApplicationService.HasCandidateAppliedForOffer(input.CandidateId, input.JobOfferId))
            {
                this.TempData["AlreadyAppliedMessage"] = GlobalConstants.CandidateAlreadyApplied;
                return this.RedirectToAction(nameof(this.All));
            }

            var jobApplicationBaseUrl = $"{this.Request.Scheme}://{this.Request.Host}/JobApplications/Details/";
            var jobApplicationId = await this.jobApplicationService.Apply(input, jobApplicationBaseUrl);

            if (jobApplicationId == null)
            {
                return this.RedirectToAction("Error", "Home");
            }
            else
            {
                this.TempData["SuccessfulApplication"] = GlobalConstants.JobApplicationSuccessfullySubmitted;
                return this.RedirectToAction(nameof(this.All));
            }
        }

        public IActionResult Details(string id)
        {
            var userId = this.userManager.GetUserId(this.User);

            var isUserRelatedToApplication = this.jobApplicationService.IsUserRelatedToJobApplication(id, userId);
            if (!isUserRelatedToApplication && !this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                return this.Forbid();
            }

            var jobApplicationDetails = this.jobApplicationService.GetJobApplicationDetails<DetailsViewModel>(id);

            if (jobApplicationDetails == null)
            {
                return this.NotFound();
            }

            jobApplicationDetails.JobApplicationStatusChangeList = this.jobApplicationStatusesService.GetAll<JobApplicationStatusDetailsView>();
            return this.View(jobApplicationDetails);
        }

        [HttpGet]
        public async Task<IActionResult> StatusChange(int statusId, string jobApplicationId)
        {
            var userId = this.userManager.GetUserId(this.User);

            var isUserRelatedToApplication = this.jobApplicationService.IsUserRelatedToJobApplication(jobApplicationId, userId);
            if (!isUserRelatedToApplication && !this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                return this.Forbid();
            }

            var currentStatusId = this.jobApplicationService.GetJobApplicationStatusId(jobApplicationId);

            if (currentStatusId == statusId)
            {
                return this.RedirectToAction(nameof(this.Details), new { id = jobApplicationId });
            }
            else
            {
                var jobApplicationBaseUrl = $"{this.Request.Scheme}://{this.Request.Host}/JobApplications/Details/";
                var newStatus = await this.jobApplicationService.ChangeJobApplicationStatus(jobApplicationId, statusId, jobApplicationBaseUrl);

                if (newStatus < 0)
                {
                    return this.RedirectToAction("Error", "Home");
                }
            }

            this.TempData["Success"] = GlobalConstants.JobApplicationStatusSuccessfullyChanged;
            return this.RedirectToAction(nameof(this.Details), new { id = jobApplicationId });
        }

        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult All(string sortOrder, int page = 1, int perPage = GlobalConstants.ItemsPerPage)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            var candidateApplications = this.jobApplicationService.GetCandidateApplications<CandidateJobApplicationsViewModel>(candidateId);

            this.ViewData["DateSortParam"] = string.IsNullOrEmpty(sortOrder) ? "date_asc" : string.Empty;
            this.ViewData["StatusSortParam"] = sortOrder == "max_status" ? "min_status" : "max_status";
            this.ViewData["PositionSortParam"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";

            candidateApplications = sortOrder switch
            {
                "name_desc" => candidateApplications.OrderByDescending(ja => ja.JobOfferPosition),
                "name_asc" => candidateApplications.OrderBy(ja => ja.JobOfferPosition),
                "max_status" => candidateApplications.OrderByDescending(ja => ja.ApplicationStatusId),
                "min_status" => candidateApplications.OrderBy(ja => ja.ApplicationStatusId),
                "date_asc" => candidateApplications.OrderBy(ja => ja.ApplicationDate),
                _ => candidateApplications.OrderByDescending(ja => ja.ApplicationDate)
            };

            var pagesCount = (int)Math.Ceiling(candidateApplications.Count() / (decimal)perPage);

            IEnumerable<CandidateJobApplicationsViewModel> paginatedApplications = candidateApplications
                .Skip(perPage * (page - 1))
                .Take(perPage)
                .ToList();

            var viewModel = new AllViewModel
            {
                JobApplications = paginatedApplications,
                CurrentPage = page,
                PagesCount = pagesCount,
            };

            return this.View(viewModel);
        }

        [AuthorizeRoles(GlobalConstants.EmployerRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult ByOffer(string jobOfferId, string sortOrder, int page = 1, int perPage = GlobalConstants.ItemsPerPage)
        {
            var employerId = this.employersService.GetEmployerIdByUsername(this.User.Identity.Name);
            if (employerId == null)
            {

Web/RecruitMe.Web/Views/JobApplications/All.cshtml
@model RecruitMe.Web.ViewModels.JobApplications.AllViewModel
@{
    ViewData["Title"] = "My Job Applications";
    var applications = Model.JobApplications.ToList();
}

<h1>@ViewData["Title"]</h1>

@if (this.TempData["AlreadyAppliedMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["AlreadyAppliedMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (this.TempData["SuccessfulApplication"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessfulApplication"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="table-responsive-sm">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Position <a style="margin: 5px" asp-action="All" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["PositionSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Applied On <a style="margin: 5px" asp-action="All" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["DateSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Application Status <a style="margin: 5px" asp-action="All" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["StatusSortParam"]"><icon class="fas fa-sort"></icon></a></th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (applications.Count == 0)
            {
                <tr>
                    <td>
                        No applications to show.
                    </td>
                </tr>
            }
            else
            {
                @foreach (var application in applications)
                {
                    <tr>
                        <td>@application.JobOfferPosition</td>
                        <td>@application.ApplicationDate.Date.ToString("dd-MM-yyyy")</td>
                        <td>@application.ApplicationStatusName</td>
                        <td>  <a class=" btn btn-primary float-left" asp-controller="JobApplications" asp-action="Details" asp-route-id="@application.Id">Details</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <nav>
        <ul class="pagination">
            @if (this.Model.CurrentPage == 1)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-left"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobApplications/All?page=@Model.PreviousPage"><icon class="fas fa-angle-left"></icon></a></li>
            }

            @for (int i = 1; i <= Model.PagesCount; i++)
            {
                var active = i == this.Model.CurrentPage ? "active" : string.Empty;

                <li class="page-item @active"><a class="page-link" style="margin: 5px" href="~/JobApplications/All?page=@i">@i</a></li>
            }

            @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.PagesCount == 0)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-right"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobApplications/All?page=@Model.NextPage"><icon class="fas fa-angle-right"></icon></a></li>
            }
        </ul>
    </nav>
</div>

Web/RecruitMe.Web/Views/JobApplications/Apply.cshtml
@model RecruitMe.Web.ViewModels.JobApplications.ApplyViewModel
@{
    ViewData["Title"] = $"Submit Application for position '{Model.JobOfferDetails.Position}'";
    var documents = Model.Documents.Select(d => new SelectListItem(d.Name, d.Id.ToString()));

}

<h1>@ViewData["Title"]</h1>

@if (this.TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>

<div class="container-fluid">
    <form class="container" asp-controller="JobApplications" asp-action="Apply" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div>
            <label style="margin-left:1.5rem"><strong>Please validate your contact information:</strong></label>
            <div class="form-group">
                <label asp-for="CandidateDetails.FirstName"><strong>Name: </strong>@Model.CandidateDetails.FirstName @Model.CandidateDetails.LastName</label>
                <input hidden asp-for="CandidateDetails.FirstName" value="@Model.CandidateDetails.FirstName" />
                <span asp-validation-for="CandidateDetails.FirstName" class="text-danger"></span>
                <input hidden asp-for="CandidateDetails.LastName" value="@Model.CandidateDetails.LastName" />
                <span asp-validation-for="CandidateDetails.LastName" class="text-danger"></span>
                <br />
                <label asp-for="CandidateDetails.ApplicationUserEmail"><strong>Email: </strong>@Model.CandidateDetails.ApplicationUserEmail</label>
                <input hidden asp-for="CandidateDetails.ApplicationUserEmail" value="@Model.CandidateDetails.ApplicationUserEmail" />
                <span asp-validation-for="CandidateDetails.ApplicationUserEmail" class="text-danger"></span>
                <br />
                @if (Model.CandidateDetails.PhoneNumber != null)
                {
                    <label asp-for="CandidateDetails.PhoneNumber"><strong>Phone Number: </strong>@Model.CandidateDetails.PhoneNumber</label>
                    <input hidden asp-for="CandidateDetails.PhoneNumber" value="@Model.CandidateDetails.PhoneNumber" />
                    <span asp-validation-for="CandidateDetails.PhoneNumber" class="text-danger"></span>
                }
            </div>
            <input hidden asp-for="JobOfferId" value="@Model.JobOfferId" />
            <input hidden asp-for="CandidateId" value="@Model.CandidateId" />
            <a class=" btn btn-sm btn-primary" style="margin-left:1rem" target="_blank" asp-controller="Candidates" asp-action="UpdateProfile">Update contact information</a>
            <small class="form-text text-muted" style="margin-left:1.5rem">Changes will appear after reload</small>
        </div>
        <hr />
        <div>
            <div class="form-group">
                <label>Include a message (Optional):</label>
                <textarea asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>

            </div>
            <hr />
            <div class="form-group">
                <label>Select documents to attach: </label>
                <a class="btn btn-primary btn-sm float-right" target="_blank" asp-controller="Documents" asp-action="Upload">Add new Document</a><br />
                <small class="form-text text-muted float-right" style="display:block">Changes will appear after reload</small>
                @if (documents.Count() != 0)
                {
                    <select asp-for="DocumentIds" multiple asp-items="documents" class="form-control"></select>
                    <span asp-validation-for="DocumentIds" class="text-danger"></span>
                }
                else
                {
                    <label>No documents to show.</label>
                }
            </div>

            <input type="submit" value="Submit" class="btn btn-primary" style="margin-left:1.5rem" />
            <a class="btn btn-danger" href="javascript:history.go(-1)">Cancel</a>
        </div>
        <hr />
    </form>
</div>

Web/RecruitMe.Web/Views/JobApplications/ByOffer.cshtml
@model RecruitMe.Web.ViewModels.JobApplications.JobOfferAllApplicationsModel
@{
    ViewData["Title"] = @$"Job Applications for Position '{Model.Position}'";
    var applications = Model.JobApplications.ToList();
}

<h1 style="display:inline">@ViewData["Title"]</h1>
<a href="javascript:window.open('','_self').close()" class="btn btn-warning float-right" style="margin-right:1.5rem">Close</a>
<div class="table-responsive-sm">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Candidate Name</th>
                <th scope="col">Submitted On <a style="margin: 5px" asp-action="ByOffer" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["DateSortParam"]" asp-route-jobOfferId="@Model.JobOfferId"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Application Status <a style="margin: 5px" asp-action="ByOffer" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["StatusSortParam"]" asp-route-jobOfferId="@Model.JobOfferId"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">Candidate Education <a style="margin: 5px" asp-action="ByOffer" asp-controller="JobApplications" asp-route-sortOrder="@ViewData["EducationSortParam"]" asp-route-jobOfferId="@Model.JobOfferId"><icon class="fas fa-sort"></icon></a></th>
                <th scope="col">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @if (applications.Count == 0)
            {
                <tr>
                    <td>
                        No applications to show.
                    </td>
                </tr>
            }
            @foreach (var application in applications)
            {
                <tr>
                    <td>@application.CandidateName</td>
                    <td>@application.CreatedOn.Date.ToString("dd-MM-yyyy")</td>
                    <td>@application.ApplicationStatusName</td>
                    <td>@(application.CandidateEducation!=null?application.CandidateEducation:"-")</td>
                    <td>
                        <a class=" btn btn-primary" asp-controller="JobApplications" asp-action="Details" asp-route-id="@application.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <nav>
        <ul class="pagination">
            @if (this.Model.CurrentPage == 1)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-left"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobApplications/ByOffer?page=@Model.PreviousPage"><icon class="fas fa-angle-left"></icon></a></li>
            }

            @for (int i = 1; i <= Model.PagesCount; i++)
            {
                var active = i == this.Model.CurrentPage ? "active" : string.Empty;

                <li class="page-item @active"><a class="page-link" style="margin: 5px" href="~/JobApplications/ByOffer?page=@i">@i</a></li>
            }

            @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.PagesCount == 0)
            {
                <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-right"></icon></a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" style="margin: 5px" href="~/JobApplications/ByOffer?page=@Model.NextPage"><icon class="fas fa-angle-right"></icon></a></li>
            }
        </ul>
    </nav>
</div>

Web/RecruitMe.Web/Views/JobApplications/Details.cshtml
@model RecruitMe.Web.ViewModels.JobApplications.DetailsViewModel
@using RecruitMe.Common
@{
    ViewData["Title"] = $"Application Details for Position '{Model.JobOfferPosition}'";
    var acceptStatusId = Model.JobApplicationStatusChangeList.Where(jas => jas.Name.ToLower().Contains("accepted")).Select(jas => jas.Id).FirstOrDefault();
    var rejectStatusId = Model.JobApplicationStatusChangeList.Where(jas => jas.Name.ToLower().Contains("rejected")).Select(jas => jas.Id).FirstOrDefault();
    var retractStatusId = Model.JobApplicationStatusChangeList.Where(jas => jas.Name.ToLower().Contains("retracted")).Select(jas => jas.Id).FirstOrDefault();

}

<h1 style="display:inline">@ViewData["Title"]</h1>
@if (this.User.IsInRole(GlobalConstants.CandidateRoleName))
{
    <a class="btn btn-warning float-right" asp-controller="JobApplications" asp-action="All">Back to List</a>
}
else if (this.User.IsInRole(GlobalConstants.EmployerRoleName))
{
    <a class="btn btn-warning float-right" asp-controller="JobApplications" asp-action="ByOffer" asp-route-jobOfferId="@Model.JobOfferId">Back to List</a>

}

<div class="card">
    <div class="card-body">
        <h5 class="card-title" style="display:inline-block">Candidate Contact Information:</h5>
        <h6 class="card-title float-right" style="display:inline-block">Application Status: <span id="applicationStatus"> @Model.ApplicationStatusName</span></h6>
        <p class="card-text"><strong>Name: </strong>@Model.CandidateName</p>
        <p class="card-text"><strong>Email: </strong>@Model.CandidateApplicationUserEmail; <strong>Phone Number: </strong>@(Model.CandidatePhoneNumber!=null?Model.CandidatePhoneNumber:"  -")</p>
        <p class="card-text"><strong>Languages: </strong>@(Model.CandidateLanguages.Count()!=0?Model.CandidateLanguages:"  -")</p>
        <p class="card-text"><strong>Skills: </strong>@(Model.CandidateSkills.Count()!=0?Model.CandidateSkills : "  -")</p>
        @if (Model.CandidateAboutMe != null)
        {
            <hr />
            <h5 class="card-title" style="display:inline-block">About Me:</h5>
            <div class="card-text">
                @Model.CandidateAboutMe
            </div>
        }

    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5 class="card-title" style="display:inline-block">Application Message:</h5>
        <p class="card-text">@Html.Raw(Model.Message)</p>
    </div>
    <div class="card-body">
        <h5 class="card-title" style="display:inline-block">Candidate Documents</h5>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">File Name</th>
                    <th scope="col">Category</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Documents.Count(); i++)
                {
                    <tr>
                        <td>@Model.Documents[i].DocumentName</td>
                        <td>@Model.Documents[i].DocumentDocumentCategoryName</td>
                        <td>
                            <a class="btn btn-primary btn-sm" asp-controller="Documents" asp-action="Download" asp-route-id="@Model.Documents[i].DocumentId" asp-route-jobApplicationId="@Model.Id">Download</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        @if (this.User.IsInRole(GlobalConstants.EmployerRoleName) && Model.ApplicationStatusName.ToLower().Contains("review"))
        {
            <div class="text-center">
                <a class="btn btn-success align-center" asp-controller="JobApplications" asp-action="StatusChange" asp-route-statusId="@acceptStatusId" asp-route-jobApplicationId="@Model.Id">Accept</a>
                <a class="btn btn-danger align-center" asp-controller="JobApplications" asp-action="StatusChange" asp-route-statusId="@rejectStatusId" asp-route-jobApplicationId="@Model.Id">Reject</a>
            </div>
        }
        @if (this.User.IsInRole(GlobalConstants.CandidateRoleName) && Model.ApplicationStatusName.ToLower().Contains("review"))
        {
            <div class="text-center">
                <a class="btn btn-danger align-center" asp-controller="JobApplications" asp-action="StatusChange" asp-route-statusId="@retractStatusId" asp-route-jobApplicationId="@Model.Id">Retract</a>
            </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var statusElement = $("#applicationStatus");
            if (statusElement.text().indexOf("Review") >= 0) {
                statusElement.addClass("text-warning");
            }
            else if (statusElement.text().indexOf("Accepted") >= 0) {
                statusElement.addClass("text-success");
            }
            else if (statusElement.text().indexOf("Rejected") >= 0 || statusElement.text().indexOf("Retracted") >= 0) {
                statusElement.addClass("text-danger");
            }
            else {
                statusElement.classList.add("text-secondary");
            }
        });
    </script>
}