Web/RecruitMe.Web/Controllers/DocumentsController.cs
namespace RecruitMe.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RecruitMe.Common;
    using RecruitMe.Data.Models;
    using RecruitMe.Services;
    using RecruitMe.Services.Data;
    using RecruitMe.Web.Infrastructure.Attributes;
    using RecruitMe.Web.ViewModels.Documents;

    public class DocumentsController : BaseController
    {
        private readonly IDocumentsService documentsService;
        private readonly ICandidatesService candidatesService;
        private readonly IFileExtensionsService fileExtensionsService;
        private readonly IDocumentCategoriesService documentCategoriesService;
        private readonly IJobApplicationService jobApplicationService;
        private readonly IMimeMappingService mimeMappingService;
        private readonly UserManager<ApplicationUser> userManager;

        private IEnumerable<string> allowedExtensions;
        private IEnumerable<CategoriesDropDownViewModel> allowedCategories;

        public DocumentsController(
            IDocumentsService documentsService,
            ICandidatesService candidatesService,
            IFileExtensionsService fileExtensionsService,
            IDocumentCategoriesService documentCategoriesService,
            IJobApplicationService jobApplicationService,
            IMimeMappingService mimeMappingService,
            UserManager<ApplicationUser> userManager)
        {
            this.documentsService = documentsService;
            this.candidatesService = candidatesService;
            this.fileExtensionsService = fileExtensionsService;
            this.documentCategoriesService = documentCategoriesService;
            this.jobApplicationService = jobApplicationService;
            this.mimeMappingService = mimeMappingService;
            this.userManager = userManager;

            this.allowedExtensions = this.fileExtensionsService.GetAll();
            this.allowedCategories = this.documentCategoriesService.GetAll<CategoriesDropDownViewModel>();
        }

        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult All(int page = 1, int perPage = GlobalConstants.ItemsPerPage)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            var documents = this.documentsService.GetAllDocumentsForCandidate<DocumentsViewModel>(candidateId);

            var pagesCount = (int)Math.Ceiling(documents.Count() / (decimal)perPage);

            var paginatedDocuments = documents
                .Skip(perPage * (page - 1))
                .Take(perPage)
                .ToList();

            var viewModel = new CandidateDocumentsViewModel
            {
                Documents = paginatedDocuments,
                CurrentPage = page,
                PagesCount = pagesCount,
            };

            return this.View(viewModel);
        }

        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public IActionResult Upload()
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);

            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            var viewModel = new UploadInputModel
            {
                FileExtensions = this.allowedExtensions,
                Categories = this.allowedCategories,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Upload(UploadInputModel input)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            if (!this.ModelState.IsValid)
            {
                input.FileExtensions = this.allowedExtensions;
                input.Categories = this.allowedCategories;
                return this.View(input);
            }

            if (this.documentsService.DocumentNameAlreadyExists(input.SanitizedFileName, candidateId))
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.DocumentAlreadyExists);
                input.FileExtensions = this.allowedExtensions;
                input.Categories = this.allowedCategories;
                return this.View(input);
            }

            if (!this.allowedExtensions.Any(ae => input.File.FileName.EndsWith(ae)))
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.FileExtensionNotSupported);
                input.FileExtensions = this.allowedExtensions;
                input.Categories = this.allowedCategories;
                return this.View(input);
            }

            if (this.documentsService.GetDocumentCountForCandidate(candidateId) > 15)
            {
                this.ModelState.AddModelError(string.Empty, GlobalConstants.FIleCountReached);
                input.FileExtensions = this.allowedExtensions;
                input.Categories = this.allowedCategories;
                return this.View(input);
            }

            var documentId = await this.documentsService.UploadAsync(input, candidateId);

            if (documentId == null)
            {
                return this.RedirectToAction("Error", "Home");
            }

            this.TempData["Success"] = GlobalConstants.DocumentSuccessfullyUploaded;
            return this.RedirectToAction(nameof(this.All));
        }

        [HttpGet]
        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(string id)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            var isOwner = this.documentsService.IsCandidateOwnerOfDocument(candidateId, id);

            if (!isOwner)
            {
                return this.Forbid();
            }

            var viewModel = this.documentsService.GetDocumentDetails<DeleteViewModel>(id);

            return this.View(viewModel);
        }

        [HttpPost]
        [AuthorizeRoles(GlobalConstants.CandidateRoleName, GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
            if (candidateId == null)
            {
                return this.RedirectToAction("CreateProfile", "Candidates");
            }

            var isOwner = this.documentsService.IsCandidateOwnerOfDocument(candidateId, id);

            if (!isOwner)
            {
                return this.Forbid();
            }

            var deletionResult = await this.documentsService.DeleteAsync(id);

            if (deletionResult == false)
            {
                return this.NotFound();
            }

            this.TempData["Success"] = GlobalConstants.DocumentSuccessfullyDeleted;
            return this.RedirectToAction(nameof(this.All));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Download(string id, string jobApplicationId = null)
        {
            if (jobApplicationId == null)
            {
                var candidateId = this.candidatesService.GetCandidateIdByUsername(this.User.Identity.Name);
                if (candidateId == null)
                {
                    return this.RedirectToAction("CreateProfile", "Candidates");
                }

                var isOwner = this.documentsService.IsCandidateOwnerOfDocument(candidateId, id);
                if (!isOwner)
                {
                    return this.Forbid();
                }
            }
            else
            {
                var userId = this.userManager.GetUserId(this.User);

                var isUserRelatedToJobApplication = this.jobApplicationService.IsUserRelatedToJobApplication(jobApplicationId, userId);
                if (!isUserRelatedToJobApplication)
                {
                    return this.Forbid();
                }
            }

            var fileAsByteArray = await this.documentsService.DownloadAsync(id);
            if (fileAsByteArray == null)
            {
                return this.NotFound();
            }

            var fileName = this.documentsService.GetDocumentNameById(id);
            var contentType = this.mimeMappingService.Map(fileName);

            return this.File(fileAsByteArray, contentType, fileName);
        }
    }
}

Web/RecruitMe.Web/Views/Documents/All.cshtml
@model RecruitMe.Web.ViewModels.Documents.CandidateDocumentsViewModel
@using RecruitMe.Common
@{
    ViewData["Title"] = "My Documents";
    var documents = Model.Documents.ToList();

}

<h1>@ViewData["Title"]</h1>

@if (this.TempData["Success"] != null)
{
<div class="alert alert-success alert-dismissible fade show" role="alert">
    @TempData["Success"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
}

<div class="table-responsive-sm">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">
                    <i class="far fa-file"></i>
                </th>
                <th scope="col">File Name</th>
                <th scope="col">Category</th>
                <th scope="col">File Size</th>
                <th scope="col">Uploaded On</th>
                <th style="text-align:center">
                    @if (documents.Count < 15)
                    {
                    <a class=" btn btn-success float-left" asp-controller="Documents" asp-action="Upload">Upload</a>
                    }
                    else
                    {
                    <label class="text-danger float-right"><small><strong>@GlobalConstants.FIleCountReached</strong></small></label>
                    }
                </th>
            </tr>
        </thead>
        <tbody>
            @if (documents.Count == 0)
            {
            <tr>
                <td>
                    No documents to show.
                </td>
            </tr>
            }
            @foreach (var document in documents)
            {
                var fileSize = (document.Size < 1024 ? @document.Size + " KB" : Math.Round(@document.Size / 1024m, 2) + " MB");
            <tr>
                <td><icon class="documentIcons" name="@document.FileExtensionName"></icon></td>
                <td>@document.Name</td>
                <td>@document.DocumentCategoryName</td>
                <td>@fileSize</td>
                <td>@document.UploadedOn</td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-controller="Documents" asp-action="Download" asp-route-id="@document.Id">Download</a>
                    <a class="btn btn-danger btn-sm" target="_blank" asp-controller="Documents" asp-action="Delete" asp-route-id="@document.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <nav>
        <ul class="pagination">
            @if (this.Model.CurrentPage == 1)
            {
            <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-left"></icon></a></li>
            }
            else
            {
            <li class="page-item"><a class="page-link" style="margin: 5px" href="~/Documents/All?page=@Model.PreviousPage"><icon class="fas fa-angle-left"></icon></a></li>
            }

            @for (int i = 1; i <= Model.PagesCount; i++)
            {
                var active = i == this.Model.CurrentPage ? "active" : string.Empty;

            <li class="page-item @active"><a class="page-link" style="margin: 5px" href="~/Documents/All?page=@i">@i</a></li>
            }

            @if (this.Model.CurrentPage == this.Model.PagesCount || this.Model.PagesCount == 0)
            {
            <li class="page-item disabled"><a class="page-link" style="margin: 5px" href="#"><icon class="fas fa-angle-right"></icon></a></li>
            }
            else
            {
            <li class="page-item"><a class="page-link" style="margin: 5px" href="~/Documents/All?page=@Model.NextPage"><icon class="fas fa-angle-right"></icon></a></li>
            }
        </ul>
    </nav>
</div>

@section Scripts{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var iconElements = $(".documentIcons").toArray();
            jQuery.each(iconElements, function () {
                var elementName = this.getAttribute("name");
                if (elementName.includes("doc")) {
                    this.classList.add("far");
                    this.classList.add("fa-file-word");
                }
                else if (elementName === "pdf") {
                    this.classList.add("far");
                    this.classList.add("fa-file-pdf");
                }
                else if (elementName === "jpeg" || elementName === "jpg" || elementName === "png") {
                    this.classList.add("far");
                    this.classList.add("fa-image");
                }
                else if (elementName === "eml" || elementName === "msg") {
                    this.classList.add("far");
                    this.classList.add("fa-envelope-open");
                }
                else {
                    this.classList.add("far");
                    this.classList.add("fa-file-alt");
                }
            });
        });
    </script>
}

Web/RecruitMe.Web/Views/Documents/Delete.cshtml
@model RecruitMe.Web.ViewModels.Documents.DeleteViewModel
@{
    ViewData["Title"] = @$"Delete Document";
}

<h1 style="display:inline">@ViewData["Title"]</h1>
<hr />

<h3>Are you sure you want to delete the following Document?</h3>
<br />
<div>
    <form method="post">
        <div class="form-group">
            <h5><strong>File Name: </strong> @Model.Name</h5>
        </div>
        <br />
        <input type="submit" value="Delete" class="btn btn-danger" asp-controller="Documents" asp-action="DeleteConfirmed" asp-route-id="@Model.Id" />
        <a href="javascript:window.open('','_self').close()" class="btn btn-warning">Back</a>
    </form>
</div>

Web/RecruitMe.Web/Views/Documents/Upload.cshtml
@model RecruitMe.Web.ViewModels.Documents.UploadInputModel
@{
    ViewData["Title"] = "Upload new file";
    var allowedFileExtensions = string.Join(", ", this.Model.FileExtensions);
    var categories = this.Model.Categories.Select(c => new SelectListItem(c.Name, c.Id.ToString()));
    bool shouldHaveSkipButton = false;
}

<h1>@ViewData["Title"]</h1>
@if (this.TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    shouldHaveSkipButton = true;
}
<h3>Add documents to your portfolio to use in your job applications</h3>
<div class="container-fluid">
    <form class="container" asp-controller="Documents" asp-action="Upload" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label>Allowed file extensions: @allowedFileExtensions</label>
                    <label>Max Size allowed: 10MB</label>
                    <label class="text-danger float-right"><small><strong>Required</strong></small></label>
                    <input asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="DocumentCategoryId"></label>
                    <label class="text-danger float-right"><small><strong>Required</strong></small></label>
                    <select asp-for="DocumentCategoryId" asp-items="categories" class="form-control"></select>
                    <span asp-validation-for="DocumentCategoryId" class="text-danger"></span>
                </div>

                <input style="margin-left: 1.5rem;" type="submit" value="Upload" class="btn btn-primary" />
                @if (shouldHaveSkipButton)
                {
                    <a class="btn btn-warning" style="margin-left:0.5rem" asp-controller="JobOffers" asp-action="All">Skip</a>
                }
                else
                {
                    <a id="cancelButton" class="btn btn-danger" style="margin-left:0.5rem">Back</a>
                }
                <hr />
            </div>
        </div>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        $("#cancelButton").attr("href", "http://www.google.com/")

        if (window.opener != null) {
            //PopUp
            $("#cancelButton").attr("href", "javascript:window.open('','_self').close()");
        }
        else {
            $("#cancelButton").attr("href", "javascript:history.go(-1)");
        }
    });
</script>